# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="mupdf"
export FILE="lf"

# Home directory clean-up
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export LESSHISTFILE="-" # no history file for less




# to avoid blank screen on start of GoLand in dwm
export _JAVA_AWT_WM_NONREPARENTING=1

export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '


# set caps lock as a secondary escape key
setxkbmap -option caps:escape

[[ ":$PATH:" != *":$HOME/.cargo/bin:$HOME/go/bin:/usr/local/go/bin:"* ]] && PATH="$HOME/.cargo/bin:$HOME/go/bin:/usr/local/go/bin:$PATH"
